server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: false
        ddl-auto: validate
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    default-schema: PUBLIC
    contexts: dev

  security:
    enabled: false

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.liquibase: INFO